// Hand-kept (FR-016); not generated by sync:planechase. Cards that end or undo the game, lock it,
// or hand one player runaway extra turns. They start off while no selection is saved (FR-017);
// once one is saved, it alone decides (FR-018). Ids are oracle ids, stable across reprints.
export const DEFAULT_OFF_IDS: readonly string[] = [
  '29e3371d-aa41-46a9-921a-96565be47eff', // Otaria
  '9c925057-ac3d-461e-b505-f80e2fd38c8c', // Temple of Atropos
  'f0c8ce35-b627-485c-bd64-d7eae47b8efa', // Sanctum of Serra
  '9d58f647-3f83-4f65-a944-c6236db7c422', // Norn's Dominion
  'a34b272b-084b-4ff1-8b02-d95116ccfeab', // Planewide Disaster
  '302e4ac2-522b-4a0a-850a-d856639ea2a4', // Morphic Tide
  '85592710-8637-4726-8b92-552b9be677c0', // Lethe Lake
  '14066888-66f6-4903-8de2-cc961aa45d8d', // Unleash the Flux
];
